version: 0.2
phases:
 install:
   runtime-versions:
     nodejs: 18
   commands:
     - npm install -g aws-cdk
 pre_build:
   commands:
     - echo "Installing dependencies..."
     - npm install
     - cd frontend
     - npm install
     - cd ..
 build:
   commands:
     - echo "Deploying CDK Stack..."
     - cdk bootstrap --stackname ServerlessStack
     - cdk deploy ServerlessStack --require-approval never
     - echo "Building React App..."
     - cd frontend
     - npm run build
     - cd ..
 post_build:
   commands:
     - echo "Deployed successfully..."
    #  - aws s3 sync frontend/build/ s3://your-s3-bucket-name --delete
    #  - echo "Invalidating CloudFront Cache..."
    #  - aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"